version: '2.4'

services:
  db:
    image: postgres:15
    container_name: backend-carrito-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carrito_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: backend-carrito:latest
    container_name: backend-carrito-app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: carrito_db
      PYTHONPATH: /app
    command: tail -f /dev/null
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  tests:
    build: .
    image: backend-carrito:latest
    container_name: backend-carrito-tests
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - .:/app:delegated
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=carrito_db
    command: pytest -q

volumes:
  db_data:
