version: '3.8'

services:
  app:
    build: .
    image: backend-carrito:latest
    container_name: backend-carrito-app
    working_dir: /app
    command: tail -f /dev/null
    volumes:
      - .:/app:delegated

  tests:
    build: .
    image: backend-carrito:latest
    container_name: backend-carrito-tests
    depends_on:
      - app
    working_dir: /app
    volumes:
      - .:/app:delegated
    environment:
      - PYTHONPATH=/app
    command: pytest -q
