[project]
name = "backend-carrito"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.3",
    "pytest-bdd>=8.1.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "locust>=2.44.0",
    "pytest>=9.0.3",
    "pytest-bdd>=8.1.0",
    "pytest-html>=4.2.0",
]
